module.exports = {
  testEnvironment: "node",
  setupFilesAfterEnv: ["<rootDir>/setup.js"],
  moduleNameMapper: {
    "^uuid$": "<rootDir>/tests/__mocks__/uuid.js",
  },
  testMatch: [
    "<rootDir>/tests/**/*.test.js",
    "<rootDir>/**/__tests__/**/*.test.js",
  ],
  testPathIgnorePatterns: ["/node_modules/"],
  transformIgnorePatterns: [
    "/node_modules/(?!(@vercel/sdk|uuid)/)",
  ],
  collectCoverageFrom: [
    "src/**/*.js",
    "routes/**/*.js",
    "!**/node_modules/**",
    "!**/coverage/**",
    "!**/__tests__/**",
    "!**/test/**",
    "!src/legacy/data-scientist/**",
    "!src/legacy/photographer/**",
    "!src/legacy/software-engineer/**",
    "!src/modules/emailmvp/**",
    "!src/modules/portfolios/agentPortfolioGenerator.service.js",
    "!src/shared/utils/multer.js",
    "!src/shared/utils/cloudinaryUpload.js",
    "!src/modules/users/users.controller.js",
    "!src/modules/portfolios/portfolio.controller.js",
    "!src/modules/payments/domain-payment/stripe/stripe.controller.js",
    "!src/modules/portfolios/portfolio.service.js",
    "!src/modules/domains/DomainRouter/DomainRouter.controller.js",
    "!src/modules/domains/domain.service.js",
    "!src/modules/domains/vercel.service.js",
    "!src/modules/domains/DomainRouter/DomainRouter.service.js",
    "!src/modules/domains/DomainRouter/utils/domainHelpers.js",
    "!src/legacy/handyman/**",
    "!src/legacy/project-manager/**",
    "!src/modules/telemetry/**",
    "!src/modules/index.js",
    "!src/modules/payments/subscriptions.controller.js",
    "!src/modules/payments/stripe-webhook.routes.js",
    "!src/modules/payments/checkout.routes.js",
    "!src/modules/payments/domain-payment/services/**",
    "!src/legacy/healthcare/routes/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "text-summary", "json-summary", "lcov", "html"],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80,
    },
  },
  testTimeout: 30000,
  maxWorkers: 1,
  verbose: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: false,
  resetModules: true,
  restoreMocks: true,
};
