module.exports = {
  testEnvironment: "node",
  setupFilesAfterEnv: ["<rootDir>/setup.js"],
  testMatch: [
    "<rootDir>/tests/**/*.test.js",
    "<rootDir>/**/__tests__/**/*.test.js", // <- include nested __tests__
    "**/test/**/*.test.js",
  ],
  transformIgnorePatterns: ["node_modules/(?!(@vercel/sdk)/)"],
  collectCoverageFrom: [
    "routes/**/*.js",
    "models/**/*.js",
    "controllers/**/*.js",
    "!**/node_modules/**",
    "services/**/*.js",
    "!**/coverage/**",
    "**/*.js",
    "!**/node_modules/**",
    "!**/test/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  testTimeout: 30000,
  maxWorkers: 1,
  verbose: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: false,
  resetModules: true,
  restoreMocks: true,
};
