name: CI (backend)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  # keeps checks green after merge

jobs:
  build-backend:
    name: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci
      # Optional if you have them:
      - run: npm run lint --if-present
      - run: npm run build --if-present

  test-backend:
    name: test-backend
    runs-on: ubuntu-latest
    env:
      # Adjust to whatever your code reads (e.g., MONGODB_URI). Keep NODE_ENV=test.
      MONGO_URI: mongodb://127.0.0.1:27017/test-db
      NODE_ENV: test
    services:
      mongo:
        image: mongo:7
        ports: [ "27017:27017" ]
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      #Need to change according to our test
      - run: npm ci
      - run: npm test -- --ci
